# Generated by Django 2.1.3 on 2018-12-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181227_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пробег'),
        ),
    ]
